language: generic 
sudo: required 
services:
    - docker 

before_install:
    - docker build -t loesakb/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -d -e CI=true loesakb/react-test npm run start -- --coverage

after_success:
    - docker build -t loesakb/multi-client ./client
    - docker build -t loesakb/multi-nginx ./nginx
    - docker build -t loesakb/multi-server ./server
    - docker build -t loesakb/multi-worker ./worker

    #docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

    - docker push loesakb/multi-client
    - docker push loesakb/multi-nginx
    - docker push loesakb/multi-server 
    - docker push loesakb/multi-worker

deoloy:
    edge: true
    provider: elasticbeantalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    backet_name: "elasticbeanstalk-us-east-2-163853346091"
    backet_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    

